# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Preload
    before: ./before.sh
  # - init: echo "welcome to iRust"
  - name: iRust
    command: ./welcome.sh
github:
  prebuilds:
    master: true
    branches: true
    pullRequestsFromForks: true
    addLabel: prebuilt-in-gitpod
vscode:
  extensions:
    - belfz.search-crates-io
    - rust-lang.rust
    - serayuzgur.crates
    - bungcip.better-toml

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
# ports:
#   - port: 3000
#     onOpen: open-preview
