tasks:
  - name: Preload
    before: |
      rustup update stable
      cargo +stable install irust
      rustup toolchain add nightly-2022-04-06
      rustup component add rustc-dev --toolchain=nightly-2022-04-06
      cargo +nightly-2022-04-06 install racer
      cargo install cargo-edit cargo-show-asm cargo-expand
  - name: IRust
    command: |
      echo "Welcome to IRust. Just type 'irust' to begin."
      echo "Once the REPL starts, type ':help' for a list of commands."
      echo "Learn more at https://github.com/sigmaSd/IRust"
github:
  prebuilds:
    master: true
    branches: true
    pullRequestsFromForks: true
    addLabel: prebuilt-in-gitpod
vscode:
  extensions:
    - belfz.search-crates-io
    - serayuzgur.crates
    - bungcip.better-toml
