tasks:
  - name: Preload
    before: |
      rustup update stable
      cargo install --path crates/irust
      cargo install cargo-edit cargo-show-asm cargo-expand
      rustup component add rust-analyzer
      echo 'export PATH="$PATH:$(rustc --print sysroot)/bin"' >> ~/.bashrc
  - name: IRust
    command: |
      echo "Welcome to IRust. Just type 'irust' to begin."
      echo "Once the REPL starts, type ':help' for a list of commands."
      echo "Learn more at https://github.com/sigmaSd/IRust"
github:
  prebuilds:
    master: true
    branches: true
    pullRequestsFromForks: true
    addLabel: prebuilt-in-gitpod
vscode:
  extensions:
    - belfz.search-crates-io
    - serayuzgur.crates
    - bungcip.better-toml
