[workspace]
resolver = "2"

members = [
    "crates/irust",
    "crates/printer",
    "crates/irust_api",
    "crates/irust_repl",
]

[profile.release]
strip = true
lto = true


# flamegraph
# [profile.release]
# debug = true
