[workspace]

members = [
    "crates/irust",
    "crates/printer",
    "crates/irust_api",
    "crates/irust_repl",
]


exclude = [
    "scripts_examples"
]

# flamegraph
[profile.release]
debug = true
