[workspace]

members = [
    "./irust_prompt",
    "./irust_vim_dylib",
    "./ipython",
    "./fun",
    "./irust_animation",
    "./mixed_cmds"
]

[workspace.dependencies]
irust_api = { path = "../crates/irust_api/" }
rscript = "0.17.0"
