[package]
name = "irust_api"
version = "0.11.0"
authors = ["Nbiba Bedis <bedisnbiba@gmail.com>"]
edition = "2018"
description = "IRust API"
repository = "https://github.com/sigmaSd/IRust/tree/master/crates/irust_api"
license = "MIT"

[dependencies]
crossterm = "0.20.0"
rscript = "0.1.0"
serde = { version = "1.0.126", features = ["derive"] }
