[package]
name = "printer"
version = "0.2.12"
authors = ["Nbiba Bedis <bedisnbiba@gmail.com>"]
edition = "2018"
readme = "README.md"
description = "Abstraction over terminal manipulation"
repository = "https://github.com/sigmaSd/IRust/tree/master/crates/printer"
license = "MIT"

[dependencies]
crossterm = "0.21.0"
unicode-width = "0.1.8"
