[package]
name = "irust"
version = "1.65.1"
authors = ["Nbiba Bedis <bedisnbiba@gmail.com>"]
edition = "2021"
readme = "README.md"
description = "Cross Platform Rust Repl"
repository = "https://github.com/sigmaSd/IRust"
license = "MIT"

[dependencies]
crossterm = { version = "0.25.0", features = ["serde"] }
dirs = "4.0.0"
toml = "0.5.9"
serde = { version = "1.0.147", features = ["derive"] }
printer = { path = "../printer/", version = "0.5.0" }
irust_api = { path = "../irust_api/", version = "0.31.0" }
irust_repl = { path = "../irust_repl", version = "0.20.0", features = ["serde"] }
rscript = "0.17.0"
rustc_lexer = { version = "727.0.0", package = "rustc-ap-rustc_lexer" }

[target.'cfg(unix)'.dependencies]
libc = "0.2.137"

# flamegraph
# [profile.release]
# debug = true

