[package]
name = "irust_repl"
version = "0.5.0"
authors = ["Nbiba Bedis <bedisnbiba@gmail.com>"]
edition = "2018"
readme = "README.md"
description = "IRust Repl abstraction"
repository = "https://github.com/sigmaSd/IRust/tree/master/crates/irust_repl"
license = "MIT"

[dependencies]
once_cell = "1.7.2"
serde = { version = "1.0.126", features = ["derive"], optional = true }
